#ifndef SHUNT_DEFINE_H
#define SHUNT_DEFINE_H

#define SHUNT_BOTH_OFF  0
#define SHUNT_CW_ON  1
#define SHUNT_CCW_ON 2
#define SHUNT_CW_OFF  3
#define SHUNT_CCW_OFF 4
#define SHUNT_FULL_TURN_TIME 2000
#define CONTROLLER_MODE_RESET_PID 0
#define CONTROLLER_MODE_RUN_PID 1
#define CONTROLLER_MODE_PAUSE_PID 2

#endif // SHUNT_DEFINE_H
